src/Controllers/ClientController.cs
using EatAndDrink.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Net;
namespace EatAndDrink.Controllers
{
    public class ClientController : Controller
    {
        public EatAndDrinkDbContext GetContext()
        {
            return new EatAndDrinkDbContext();
        }
        public IActionResult Index()
        {
            return View(GetContext().Clients.ToList());
        }
        public IActionResult New()
        {
            return View(new ClientCreateViewModel());
        }
        public class ClientCreateViewModel
        {
            [Required]
            [Display(Name = "First name")]
            public string FirstName { get; set; }

            [Required]
            [Display(Name = "Last name")]
            public string LastName { get; set; }

            [Required]
            [Display(Name = "Phone number")]
            public string PhoneNumber { get; set; }

            [Required]
            [Display(Name = "Address")]
            public string Address { get; set; }
        }
        public async Task<IActionResult> Create(ClientCreateViewModel model)
        {
            using (var context = GetContext())
            {
                var client = new Client
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PhoneNumber = model.PhoneNumber,
                    Address = model.Address
                };
                context.Clients.Add(client);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            using (var context = GetContext())
            {
                return View(context.Clients.Find(id));
            }
        }
        public async Task<IActionResult> Update(Client model)
        {
            using (var context = GetContext())
            {
                context.Clients.Update(model);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            using (var context = GetContext())
            {
                var clients = context.Clients.Find(id);
                context.Clients.Remove(clients);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }

    //public IActionResult Index()
    //{
    //    Client client1 = new Client() { Id = 1, FirstName = "John", LastName = "Doe", PhoneNumber = "0702350302", Address = "Bishkek, Manasa 1" };
    //    Client client2 = new Client() { Id = 2, FirstName = "Ivan", LastName = "Ivanov", PhoneNumber = "0225601100", Address = "Bishkek, Manasa 2" };
    //    Client client3 = new Client() { Id = 3, FirstName = "Sergio", LastName = "Olson", PhoneNumber = "0505601100", Address = "Bishkek, Manasa 3" };
    //    Client client4 = new Client() { Id = 4, FirstName = "Ritthy", LastName = "Adams", PhoneNumber = "0559091010", Address = "Bishkek, Manasa 4" };
    //    Client client5 = new Client() { Id = 5, FirstName = "Clara", LastName = "Chapman", PhoneNumber = "0999556111", Address = "Bishkek, Manasa 5" };
    //    Client client6 = new Client() { Id = 6, FirstName = "Antonio", LastName = "Washington", PhoneNumber = "0955789054", Address = "Bishkek, Manasa 6" };
    //    Client client7 = new Client() { Id = 7, FirstName = "Rene", LastName = "Marshal", PhoneNumber = "0990897865", Address = "Bishkek, Manasa 7" };
    //    Client client8 = new Client() { Id = 8, FirstName = "Janice", LastName = "Fleming", PhoneNumber = "0998990088", Address = "Bishkek, Manasa 8" };
    //    Client client9 = new Client() { Id = 9, FirstName = "Corey", LastName = "Obrien", PhoneNumber = "0999876432", Address = "Bishkek, Manasa 9" };
    //    Client client10 = new Client() { Id = 10, FirstName = "Ritthy", LastName = "Spencer", PhoneNumber = "0999675634", Address = "Bishkek, Manasa 10" };

    //    Array array = new[] { client1, client2, client3, client4, client5, client6, client7, client8, client9, client10 };

    //    return View(array);
    //}

}
 

src/Controllers/DishController.cs
using Microsoft.AspNetCore.Mvc;

namespace EatAndDrink.Controllers
{
    public class DishController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace EatAndDrink.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace EatAndDrink.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EatAndDrink</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/EatAndDrink.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EatAndDrink</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Client"
                            asp-action="Index">Clients</a>
                        </li>
                         <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Courier"
                            asp-action="Index">Couriers</a>
                        </li>
                        <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Dish"
                            asp-action="Index">Dishs</a>
                        </li>
                          <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Menu"
                            asp-action="Index">Menu</a>
                        </li>
                         <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Order"
                            asp-action="Index">Orders</a>
                        </li>
                         <li class="nav-item">
                            <a
                            class="nav-link text-dark"
                            asp-controller="Restorant"
                            asp-action="Index">Restorant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EatAndDrink - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>